/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request an OTP for a phone number
         * @description Sends an OTP via SMS. In `development` env (and for a configured test phone number) the OTP is also returned in the response body (`otp`) and SMS is skipped, to ease local/E2E testing. Rate-limited to 3 attempts per window.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OtpRequestInput"];
                };
            };
            responses: {
                /** @description OTP issued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OtpRequestResult"];
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify an OTP and obtain an access token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OtpVerifyInput"];
                };
            };
            responses: {
                /** @description Verified; access token + user returned */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VerifyOtpResult"];
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current authenticated user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The current user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update the current user's profile
         * @description Partial update. At least one of `fullName` / `email` must be present.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateProfileInput"];
                };
            };
            responses: {
                /** @description Updated user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Validation error (e.g. "This email is already in use") */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        trace?: never;
    };
    "/users/me/addresses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's saved addresses */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Address list (may be empty) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Address"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /**
         * Create an address
         * @description Address is **location-only**. The request carries `{ label, line1, line2, pincode, isDefault }`; the server resolves `city`, `district`, `state` and `stateCode` from the pincode (a serviceability lookup). Recipient name/phone are NOT stored on an address — they come from the user's profile/account. The first address created is forced default. An unserviceable pincode → 400.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddressInput"];
                };
            };
            responses: {
                /** @description Created address (with derived city/state) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Address"];
                    };
                };
                /** @description Validation error, e.g. "Pincode 999999 is not serviceable." */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/addresses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AddressId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an address */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["AddressId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted (no content) */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /**
         * Update an address
         * @description Partial update; same field set as create. Changing `pincode` re-derives city/state.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["AddressId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddressInput"];
                };
            };
            responses: {
                /** @description Updated address */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Address"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/users/me/addresses/{id}/default": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["AddressId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set an address as the default */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["AddressId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The now-default address */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Address"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List active, approved products for a city
         * @description Server-paginated. Only `categoryId` and `city` filtering are supported; search / price / rating / sort and a total count are NOT provided by this endpoint today (the frontend applies those client-side over a fetched page).
         */
        get: {
            parameters: {
                query?: {
                    categoryId?: string;
                    city?: string;
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of products */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Product detail by slug */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Product detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductDetail"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{slug}/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Supplier listings (offers) for a product, cheapest first */
        get: {
            parameters: {
                query?: {
                    role?: string;
                    quantity?: number;
                };
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Listings ordered by price ascending (first = default for add-to-cart) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Listing"][];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List categories (optionally by parent) */
        get: {
            parameters: {
                query?: {
                    parentId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Categories */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/categories/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Category tree
         * @description Returns the category rows (each carrying `parentId`/`depthLevel`); the hierarchy is reconstructed by the client from those fields.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Categories */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/categories/{id}/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dynamic filter config for a category */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Filter configs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FilterConfig"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user's cart (enriched line items) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cart items */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CartItem"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /**
         * Add an item to the cart
         * @description Cart is keyed by `supplierProductId`. Returns the full updated cart.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddToCartInput"];
                };
            };
            responses: {
                /** @description Updated cart */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CartItem"][];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        /** Clear the cart */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Empty cart */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CartItem"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The supplierProductId of the line item */
                itemId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a cart line item */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The supplierProductId of the line item */
                    itemId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Updated cart */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CartItem"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        options?: never;
        head?: never;
        /** Update a cart line item quantity */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The supplierProductId of the line item */
                    itemId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateCartInput"];
                };
            };
            responses: {
                /** @description Updated cart */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CartItem"][];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        trace?: never;
    };
    "/cart/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check out the cart into an order
         * @description Creates an order against a saved address and returns a Razorpay order to complete payment client-side.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CheckoutInput"];
                };
            };
            responses: {
                /** @description Order created; Razorpay order returned */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CheckoutResult"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's orders */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of orders */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderList"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Order detail (with sub-orders and items) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Order detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderDetail"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Standard error envelope returned by every handler's error path. */
        Error: {
            /** @example 400 */
            statusCode: number;
            /** @example BAD_REQUEST */
            error: string;
            /** @example Invalid request body */
            message: string;
        };
        OtpRequestInput: {
            /**
             * @description 10–13 chars; +91 prefix accepted
             * @example +919876500001
             */
            phoneNumber: string;
        };
        OtpRequestResult: {
            /** @example OTP sent to 98XXXXXXXX01 */
            message: string;
            /** @example 600 */
            expiresInSeconds: number;
            /**
             * @description Present ONLY in development / for the configured test phone.
             * @example 922181
             */
            otp?: string;
        };
        OtpVerifyInput: {
            /** @example +919876500001 */
            phoneNumber: string;
            /**
             * @description Exactly 6 digits
             * @example 922181
             */
            otp: string;
        };
        VerifyOtpResult: {
            /** @description Bearer JWT (~7-day expiry; no refresh token issued) */
            accessToken: string;
            user: components["schemas"]["AuthUser"];
        };
        /** @description Compact user returned by /auth/otp/verify. */
        AuthUser: {
            /** Format: uuid */
            id: string;
            /** @example 9876500001 */
            phoneNumber: string;
            /** @example User 0001 */
            fullName: string;
            /**
             * @example [
             *       "customer"
             *     ]
             */
            roles: string[];
            isNewUser: boolean;
        };
        /** @description Full user returned by GET /auth/me and PATCH /users/me. */
        User: {
            /** Format: uuid */
            id: string;
            phoneNumber: string;
            fullName: string;
            email?: string | null;
            isVerified: boolean;
            roles: string[];
            /** Format: date-time */
            createdAt: string;
        };
        /** @description At least one field required. */
        UpdateProfileInput: {
            fullName?: string;
            /** Format: email */
            email?: string;
        };
        /** @description Location-only address. city/district/state/stateCode are derived from pincode. */
        Address: {
            /** Format: uuid */
            id: string;
            /** @example Home */
            label?: string | null;
            line1: string;
            line2?: string | null;
            /** @example 201301 */
            pincode: string;
            /** @example Noida */
            city: string;
            /** @example Gautam Buddha Nagar */
            district: string;
            /** @example Uttar Pradesh */
            state: string;
            /** @example 09 */
            stateCode: string;
            /** Format: double */
            latitude?: number | null;
            /** Format: double */
            longitude?: number | null;
            isDefault: boolean;
        };
        AddressInput: {
            /** @example Home */
            label?: string;
            line1: string;
            line2?: string;
            /** @example 201301 */
            pincode: string;
            isDefault?: boolean;
        };
        ProductList: {
            products: components["schemas"]["ProductListItem"][];
            page: number;
            limit: number;
        };
        ProductListItem: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            description?: string | null;
            hsnCode: string;
            /** @example kg */
            unitOfMeasure: string;
            attributes?: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            createdAt?: string;
            categoryName: string;
            categorySlug: string;
            primaryImage?: string | null;
            /**
             * Format: int64
             * @description Cheapest in-stock listing price in paise; null if no in-stock supply
             */
            minPricePaise?: number | null;
            /**
             * Format: uuid
             * @description Id of the cheapest in-stock listing — used for add-to-cart from a card
             */
            defaultSupplierProductId?: string | null;
            /** Format: int64 */
            supplierCount: number;
        };
        ProductDetail: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            description?: string | null;
            hsnCode: string;
            unitOfMeasure: string;
            attributes?: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            approvedAt?: string | null;
            categoryName: string;
            categorySlug: string;
            gst: {
                /** Format: double */
                cgstPct?: number;
                /** Format: double */
                sgstPct?: number;
                /** Format: double */
                igstPct?: number;
            };
            images?: {
                /** Format: uuid */
                id?: string;
                url?: string;
                order?: number;
            }[] | null;
        };
        Listing: {
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            pricePaise: number;
            /**
             * Format: int64
             * @description Role/quantity-resolved price
             */
            effectivePricePaise: number;
            minOrderQuantity: number;
            leadTimeDays: number;
            isActive: boolean;
            /** Format: int64 */
            availableStock: number;
            supplierName: string;
            /** Format: uuid */
            supplierId: string;
        };
        Category: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            parentId?: string | null;
            name: string;
            slug: string;
            depthLevel: number;
            iconUrl?: string | null;
            displayOrder: number;
        };
        FilterConfig: {
            attributeKey?: string;
            displayLabel?: string;
            /** @enum {string} */
            filterType?: "range" | "multi_select" | "boolean";
            displayOrder?: number;
        };
        CartItem: {
            /** Format: uuid */
            supplierProductId: string;
            quantity: number;
            /** Format: date-time */
            addedAt: string;
            /** Format: uuid */
            productId: string;
            productName: string;
            productSlug: string;
            unitOfMeasure: string;
            /** Format: uuid */
            supplierId: string;
            supplierName: string;
            /** Format: int64 */
            pricePaise: number;
            /** Format: int64 */
            availableStock: number;
            minOrderQuantity: number;
            hsnCode: string;
            primaryImageUrl?: string | null;
        };
        AddToCartInput: {
            /** Format: uuid */
            supplierProductId: string;
            quantity: number;
        };
        UpdateCartInput: {
            quantity: number;
        };
        CheckoutInput: {
            /** Format: uuid */
            addressId: string;
            buyerGstin?: string | null;
        };
        CheckoutResult: {
            /** Format: uuid */
            orderId: string;
            orderNumber: string;
            /** Format: int64 */
            totalPaise: number;
            razorpayOrderId: string;
            razorpayKeyId: string;
        };
        OrderList: {
            items: components["schemas"]["OrderListItem"][];
            page: number;
            limit: number;
            /** Format: int64 */
            total: number;
        };
        OrderListItem: {
            /** Format: uuid */
            id: string;
            orderNumber: string;
            status: string;
            /** Format: int64 */
            subtotalPaise: number;
            /** Format: int64 */
            gstAmountPaise: number;
            /** Format: int64 */
            totalPaise: number;
            razorpayOrderId?: string;
            /** Format: date-time */
            placedAt: string;
            /** Format: date-time */
            confirmedAt?: string | null;
            addressLine1?: string;
            addressCity?: string;
            addressState?: string;
            addressPincode?: string;
            /** Format: int64 */
            subOrderCount?: number;
            /** Format: int64 */
            itemCount?: number;
        };
        OrderDetail: {
            /** Format: uuid */
            id: string;
            orderNumber: string;
            status: string;
            /** Format: int64 */
            subtotalPaise: number;
            /** Format: int64 */
            gstAmountPaise: number;
            /** Format: int64 */
            discountPaise: number;
            /** Format: int64 */
            totalPaise: number;
            buyerGstin?: string | null;
            razorpayOrderId?: string | null;
            /** Format: date-time */
            placedAt?: string;
            /** Format: date-time */
            confirmedAt?: string | null;
            address: {
                line1?: string | null;
                line2?: string | null;
                city?: string | null;
                district?: string | null;
                state?: string | null;
                pincode?: string | null;
            };
            subOrders: components["schemas"]["SubOrder"][];
        };
        SubOrder: {
            /** Format: uuid */
            id?: string;
            status?: string;
            /** Format: int64 */
            subtotalPaise?: number;
            /** Format: int64 */
            gstAmountPaise?: number;
            /** Format: int64 */
            totalPaise?: number;
            payoutStatus?: string | null;
            ewayBillNumber?: string | null;
            /** Format: date-time */
            dispatchedAt?: string | null;
            /** Format: date-time */
            deliveredAt?: string | null;
            supplierName?: string;
            /** Format: uuid */
            supplierId?: string;
            items?: components["schemas"]["OrderItem"][];
        };
        OrderItem: {
            /** Format: uuid */
            id?: string;
            quantity?: number;
            /** Format: int64 */
            unitPricePaise?: number;
            hsnCode?: string;
            /** Format: double */
            gstRatePct?: number;
            /** Format: int64 */
            cgstPaise?: number;
            /** Format: int64 */
            sgstPaise?: number;
            /** Format: int64 */
            igstPaise?: number;
            /** Format: int64 */
            lineTotalPaise?: number;
            productNameSnapshot?: string;
            /** Format: uuid */
            productId?: string;
            /** Format: uuid */
            supplierProductId?: string;
            productSlug?: string;
            primaryImage?: string | null;
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid Authorization header */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authenticated but not permitted */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        AddressId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
